site_name: Vetiver
nav:
    - Home: index.md
    - Get Started: get-started.md
    - VetiverModel: vetiver-model.md
    - VetiverAPI: vetiver-api.md
    - Examples: examples.md
theme:
  logo: amphora.png
  icon:
    repo: fontawesome/brands/github
  name: material
  features:
    - navigation.expand
    - navigation.tabs.sticky
  palette:
    primary: white
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
repo_url: https://github.com/isabelizimm/vetiver-python
repo_name: isabelizimm/vetiver-python
