name: tests

on:
  workflow_dispatch:
  push:
    branches: ['main', 'dev-*', 'dev']
  pull_request:
  release:
    types: [published]

jobs:
  tests:
    name: "Tests"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: 'ubuntu-latest'
            python-version: '3.7'
          - os: 'macos-latest'
            python-version: '3.8'
          - os: 'windows-latest'
            python-version: '3.9'
          - os: 'ubuntu-latest'
            python-version: '3.10'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev,torch]
      - name: Run Tests
        run: |
          pytest --cov --cov-report xml .
      - name: Upload coverage
        uses: codecov/codecov-action@v2
